models:
- model_name: mistralai/ministral-3b-2512
  litellm_params:
    model: openai/ministral-3b-latest
    api_base: https://api.mistral.ai/v1
    api_key: os.environ/MISTRAL_API_KEY
  model_info:
    access_groups: ["public", "private"]
