models:
- model_name: mistralai/mistral-small-2603
  litellm_params:
    model: openai/mistral-small-latest
    api_base: https://api.mistral.ai/v1
    api_key: os.environ/MISTRAL_API_KEY
  model_info:
    access_groups: ["public", "private"]
