models:
- model_name: mistralai/mistral-medium-3-5
  litellm_params:
    model: openai/mistralai/mistral-medium-3-5
    api_base: https://openrouter.ai/api/v1
    api_key: os.environ/OPENROUTER_API_KEY
  model_info:
    access_groups: ["public", "private"]
