models:
- model_name: Qwen3.8-27B
  litellm_params:
    model: huggingface/Qwen/Qwen3.8-27B:cerebras
    api_base: https://router.huggingface.co/v1
    api_key: os.environ/HF_TOKEN
    drop_params: true 
    extra_headers:
      X-HF-Bill-To: "current-ai-official"
  model_info:
    access_groups: ["public", "private"]
- model_name: Qwen3.5-122B-A10B
  litellm_params:
    model: huggingface/Qwen/Qwen3.5-122B-A10B:deepinfra
    api_base: https://router.huggingface.co/v1
    api_key: os.environ/HF_TOKEN
    extra_headers:
      X-HF-Bill-To: "current-ai-official"
  model_info:
    access_groups: ["public", "private"]
- model_name: Qwen3-235B-A22B-Thinking-2507
  litellm_params:
    model: huggingface/Qwen/Qwen3-235B-A22B-Thinking-2507:deepinfra
    api_base: https://router.huggingface.co/v1
    api_key: os.environ/HF_TOKEN
    extra_headers:
      X-HF-Bill-To: "current-ai-official"
  model_info:
    access_groups: ["public", "private"]
- model_name: Qwen3.5-4B
  litellm_params:
    model: huggingface/Qwen/Qwen3.5-4B:featherless-ai
    api_base: https://router.huggingface.co/v1
    api_key: os.environ/HF_TOKEN
    extra_headers:
      X-HF-Bill-To: "current-ai-official"
  model_info:
    access_groups: ["public", "private"]
- model_name: Qwen3.5-35B-A3B
  litellm_params:
    model: huggingface/Qwen/Qwen3.5-35B-A3B:deepinfra
    api_base: https://router.huggingface.co/v1
    api_key: os.environ/HF_TOKEN
    extra_headers:
      X-HF-Bill-To: "current-ai-official"
  model_info:
    access_groups: ["public", "private"]
- model_name: Qwen3.5-9B
  litellm_params:
    model: huggingface/Qwen/Qwen3.5-9B:together
    api_base: https://router.huggingface.co/v1
    api_key: os.environ/HF_TOKEN
    extra_headers:
      X-HF-Bill-To: "current-ai-official"
  model_info:
    access_groups: ["public", "private"]
