models:
- model_name: Cloudflare/clef
  litellm_params:
    model: cloudflare/@cf/cloudflare/clef
    api_key: os.environ/CLOUDFLARE_API_KEY
    supports_vision: true
  model_info:
    access_groups: ["public", "private"]