models:
- model_name: CohereLabs/tiny-aya-earth
  litellm_params:
    model: huggingface/CohereLabs/tiny-aya-earth:cohere
    api_base: https://router.huggingface.co/v1
    api_key: os.environ/HF_TOKEN
    extra_headers:
      X-HF-Bill-To: "current-ai-official"
  model_info:
    access_groups: ["public", "private"]
