models:
- model_name: zai-org/GLM-5.3
  litellm_params:
    model: huggingface/zai-org/GLM-5.3:novita
    api_base: https://router.huggingface.co/v1
    api_key: os.environ/HF_TOKEN
    extra_headers:
      X-HF-Bill-To: "current-ai-official"
  model_info:
    access_groups: ["private"]
- model_name: zai-org/GLM-5.3
  litellm_params:
    model: huggingface/zai-org/GLM-5.3:together
    api_base: https://router.huggingface.co/v1
    api_key: os.environ/HF_TOKEN
    extra_headers:
      X-HF-Bill-To: "current-ai-official"
  model_info:
    access_groups: ["private"]
- model_name: zai-org/GLM-5.3
  litellm_params:
    model: huggingface/zai-org/GLM-5.3:zai-org
    api_base: https://router.huggingface.co/v1
    api_key: os.environ/HF_TOKEN
    extra_headers:
      X-HF-Bill-To: "current-ai-official"
  model_info:
    access_groups: ["private"]
- model_name: zai-org/GLM-5.3
  litellm_params:
    model: huggingface/zai-org/GLM-5.3:deepinfra
    api_base: https://router.huggingface.co/v1
    api_key: os.environ/HF_TOKEN
    extra_headers:
      X-HF-Bill-To: "current-ai-official"
  model_info:
    access_groups: ["private"]