apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agent-service.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Release.Name }}-app
  ports:
    - port: 80
      targetPort: {{ .Values.app.port }}
