apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-app-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agent-service.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.app.pvcSize }}
