{{- if .Values.externalSecret.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.app.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agent-service.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | default "1h" | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name | default "aws-secretsmanager" }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind | default "ClusterSecretStore" }}
  target:
    name: {{ .Values.app.secretName }}
    creationPolicy: {{ dig "target" "creationPolicy" "Owner" .Values.externalSecret }}
    deletionPolicy: {{ dig "target" "deletionPolicy" "Retain" .Values.externalSecret }}
  dataFrom:
    - extract:
        key: {{ dig "app" "remoteKey" (default .Values.externalSecret.remoteKey "/agent-service") .Values.externalSecret | quote }}
{{- if ne .Values.app.secretName .Values.proxy.secretName }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.proxy.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agent-service.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | default "1h" | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name | default "aws-secretsmanager" }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind | default "ClusterSecretStore" }}
  target:
    name: {{ .Values.proxy.secretName }}
    creationPolicy: {{ dig "target" "creationPolicy" "Owner" .Values.externalSecret }}
    deletionPolicy: {{ dig "target" "deletionPolicy" "Retain" .Values.externalSecret }}
  dataFrom:
    - extract:
        key: {{ dig "proxy" "remoteKey" (default .Values.externalSecret.remoteKey "/agent-service") .Values.externalSecret | quote }}
{{- end }}
{{- end }}
