apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agent-service.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Release.Name }}-proxy
  ports:
    - port: {{ .Values.proxy.port }}
      targetPort: {{ .Values.proxy.port }}
