models:
- model_name: aisingapore/Nemotron-SEA-LION-v4.8-120B-A12B
  litellm_params:
    model: openai/aisingapore/Nemotron-SEA-LION-v4.8-120B-A12B
    api_base: https://api.sea-lion.ai
    api_key: os.environ/SEALION_API_KEY
    supports_vision: true
  model_info:
    access_groups: ["public", "private"]
